config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'ahmed', to: 'people#get_ahmed'
  post 'ahmed', to: 'people#post_ahmed'
  get 'signup', to: 'users#new'
  
  resources :articles
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    # before_save {self.email = email.downcase}
    validates :title, presence: true, length: {minimum: 5, maximum: 30}
    validates :description, presence: true, length: {minimum: 10, maximum: 500}
    validates :user_id, presence: true
end 

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    validates :username, presence: true, 
    uniqueness: {case_sensitive: false},
    length: {minimum: 3, maximum: 25}

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, length: { minimum: 0, maximum: 25}, 
    uniqueness: {case_sensitive: false},
    format: {with: VALID_EMAIL_REGEX, message: "Must be a valid email address!"}
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    # helper method allows you to access these methods in views
    helper_method :current_user, :logged_in?

    def current_user
        # Find user session if the session has a user id
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        # memoization, only looks for current user once
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article =Article.new(article_params)
        @article.user = current_user
        # render plain: "#{params}. #{article_params}"
        if @article.save
            flash[:success] = "Article was successfully saved"
            redirect_to article_path(@article)
        else
            render 'new'
        end 
        
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end 

    def index
        @articles = Article.paginate(page: params[:page], per_page: 1)
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:danger] = "Article was successfully destroyed"
        redirect_to articles_path
    end

    def show
        @article = Article.find(params[:id])
    end

    private
    
    def article_params
        params.require(:article).permit(:title, :description, :user_id)
    end

    def require_same_user
        if current_user != @article.user
            flash[:danger] = "You can only edit or delete your own articles"
        end

    end

    
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end

end 

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    protect_from_forgery with: :null_session

    def get_ahmed
        render plain: "Ayyy AhmedBro. #{params}"
    end

    def post_ahmed
        render plain: "This is a post request. Post Requests are different because they have secret info. #{params}"
    end

    def render_view
        render view: "articles/new.html"
    end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        # This is the log-in action
        # use debugger to see that params[session][email] yields the email address
        user = User.find_by(email: params[:session][:email].downcase)

        if user && user.authenticate(params[:session][:password])
            #here you are saving user_id in settings hash, whih is backed by browser's cookies
            session[:user_id] = user.id
            username= User.find(user.id).username
            flash[:success] = "Welcome, #{username}!"
            redirect_to articles_path
        else
            # flash.now becasue it works with "render", which is not a redirect
            # flash[default] works with redirect only
            flash.now[:danger] = "Use Username: admin , Password: 'greathire' "
            render 'new'
        end
    end

    def destroy
        # this is the logout action
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to articles_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_same_user, only: [:edit, :update]

    def new
        @user = User.new
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
        
    end

    def create
        @user = User.new(user_params)
        if params["user"]["password"] == params["user"]["password_confirm"]
            if @user.valid?
                @user.save 
                session[:user_id] = @user.id
                redirect_to articles_path
                flash[:success] = "Welcome, #{@user.username}"
            else
                render 'new'
            end
        else
            flash[:danger] = "Please enter matching password"
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def show
        @user = User.find(params[:id])
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 1)
    end

    def update
        @user = User.find(params[:id])
        if params["user"]["password"] == params["user"]["password_confirm"]
            if @user.valid?
                @user.save 
                redirect_to articles_path
                flash[:success] = "You have successfully update your account, #{@user.username}!"
            else
                flash[:danger] = "User not successfully updated!"
                render 'edit'
            end
        else
            flash[:danger] = "Please enter matching password"
            render 'edit'
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
    def require_same_user
        if current_user != @user
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class= "col-xs-8 col-xs-offset-2">
            <div class = "well well-lg">
                <div class= "article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class = "article-author">
                    <small> Created by: <%= link_to article.user.username, user_path(article.user) if article.user%>,
                        <%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
                <div class= "article-body">
                    <%= truncate(article.description, length: 100) %>
                </div>
                <div class= "article-actions">
                    <% if logged_in? && current_user == article.user %>
                        <%= link_to 'Edit this artcile', edit_article_path(article), class: "btn btn-xs btn-primary"%>
                        <%= link_to 'Delete', article_path(article), method: :delete, 
                        data: {confirm: "Are you sure you want to delete this artcile?"}, class: "btn btn-xs btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class = "row">
    <div class = "col-xs-12">
        <%= form_for @article, html: {class:'form-horizontal', role:'form'} do |f| %>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :title %>
                </div> 
                <div class= "col-sm-8">
                    <%= f.text_field :title, class: "form-control" , placeholder: "Title of Article", autofocus: true %>
                </div>
            </div>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :description %> 
                </div>

                <div class= "col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article"%>
                </div>

                <div class = "form-group">
                    <div class = "col-sm-10 col-xs-offset-5">
                        <%= f.submit class: 'btn btn-prmary btn-lg', id: 'create-btn'%>
                    </div>
                </div>
            </div>
        <% end %>

    <div class= "col-xs-4 col-xs-offset-5">
        <%= link_to "[Back to articles listing]", articles_path%>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align = "center">Edit an article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align= "center", class = "page-headers"> Listing all articles </h1>


<%= render 'article', obj: @articles %>

<div align = "center">
    
</div>

app/views/articles/new.html.erb
<h1 align = "center">Create an article </h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<div class = "well col-xs-8 col-xs-offset-2">
    <h3 align = "left", class = "page-header" ,id = "show-title"> <%= @article.title %></h3>
    <div class = "well-in-well">
    <p id = "articles-show-author"> Written by: <%= link_to @article.user.username , user_path(@article.user) %>
        <%= time_ago_in_words(@article.created_at) %> ago.
    </p> 
    </div>
    <hr>
    <%= simple_format(@article.description) %>
    <hr>
    <div class = "article-actions">
            <% if logged_in? && current_user == article.user %>
                <%= link_to 'Edit this artcile', edit_article_path(@article), class: "btn btn-xs btn-primary"%>
                <%= link_to 'Delete', article_path(@article), method: :delete, 
                    data: {confirm: "Are you sure you want to delete this artcile?"}, class: "btn btn-xs btn-danger" %>
            <% end %>
            <%= link_to 'View all articles', article_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

<div class= "col-xs-4 col-xs-offset-5">
        <%= link_to "[Back to articles listing]", articles_path%>
</div>

app/views/layouts/_footer.html.erb
<div class="footer panel-default">
    <div class="panel-body">
    </div>
    <div class="panel-footer">
        <small>Copyright Meezo Inc.| Webmaster mozeiny@gmail.com </small>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "App Academy Blog", root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path%></li>
        <li><%= link_to "About Us", about_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Forum Access <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <%# Crate a new article %>
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <%# THE SERACH BAR %>
      <%# <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> %>
      <% if logged_in? %>
        <% currentUser = current_user()%>
        <ul class="nav navbar-nav navbar-right">
          <li> <a href="#"> Welcome, you are logged in as <%=current_user().username%> </a> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Account Options <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit User', edit_user_path(currentUser) %></li>
              <li><%= link_to 'View Articles', user_path(currentUser) %></li>
              <li role="separator" class="divider"></li>
              <li> <%= link_to 'Log out', logout_path, method: :delete %> </li> 
            </ul>
          </li>
        </ul>
      <% else%>
        <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to 'Sign Up', signup_path %></li>
          <li> <%= link_to 'Log in!', login_path %></li>
        </ul>
      <% end%>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <div class = "row">
    <div class = "col-xs-10 col-xs-offset-1">
      <% flash.each do |name,msg| %>
        <div class= 'alert alert-<%= "#{name}" %> '>
          <a href= "#" class= "close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div> 
      <% end %>
    </div>
  </div>
  

  
  <body>
    <%= render 'layouts/navigation'%>

    <div class = "w3 container">
      <%= yield %>
    </div>

    <br>
    <br>
    <%= render 'layouts/footer'%>
  

  <%= debug(params) if Rails.env.development? %>

  </body>

</html>

app/views/pages/about.html.erb
<p> this is my about page </p>
<%= link_to 'home' , root_path %>

app/views/pages/home.html.erb
  <div class="center jumbotron">
    <h1 id = "jumbotron-header">Welcome to the AppAcademy Blog! </h1>
    <div class = "row">
      <%= link_to "Sign Up Now", signup_path, class: "btn btn-danger btn-lg"%>
      <%= link_to "Login and start browsing", login_path, class: "btn btn-primary btn-lg"%>
    </div>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
    <div class = "row">
        <div class = "col-xs-8 col-xs-offset-2">
            <div class = "panel panel-danger">
                <div class = "panel-heading">
                    <h2 class= "panel-title">
                        <%= pluralize(obj.errors.count, "error")%>
                        prohbitied this article from being saved:
                    </h2>
                    <div class = "panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li> <%=msg%> </li>
                            <% end%>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<%end%>

app/views/users/edit.html.erb
<h2 align = "center", class= "page-headers"> Hi, <%= @user.username%>. Let's edit your account information. </h2>
<hr>

<%= render 'shared/errors', obj: @user %>


<div class = "row", id = "new-row">
    <div class = "col-xs-12">
        <%= form_for(@user, html: {class:'form-horizontal', role:'form'}) do |f| %>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :email %> 
                </div>

                <div class= "col-sm-8">
                    <%= f.email_field :email, rows: 10, class: "form-control", placeholder: "Enter Email"%>
                </div>
            </div>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :password %>
                </div> 
                <div class= "col-sm-8">
                    <%= f.password_field :password, class: "form-control" , placeholder: "Enter New Password" %>
                </div>
            </div>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :password_confirm %>
                </div> 
                <div class= "col-sm-8">
                    <%= f.password_field :password_confirm, class: "form-control" , placeholder: "Confirm New Password" %>
                </div>
            </div>

                <div class = "form-group">
                    <div class = "col-sm-10 col-xs-offset-5">
                        <%= f.submit "Edit Account!", class: 'btn btn-primary btn-lg', id: 'create-btn'%>
                    </div>
                </div>
            </div>
        <% end %>
   
</div>

app/views/users/index.html.erb
<h2 align = "center", class = "page-headers"> List of All Bloggers </h2>
<hr>
<% @users.each do |user| %>
    <div align = "center">
        <ul class = "listing">
            <div class = "row">
                <div class = "well col-md-4 col-md-offset-4">
                    <li class = "article-title"> <%= link_to gravatar_for(user), user_path(user) %> </li>
                    <li class = "article-title"> <%= link_to user.username, user_path(user) %>
                    <li><small><%= pluralize(user.articles.count, "article" ) if user.articles %></small> </li>
                </div>
            </div>
        </div>
    </div>
<% end %>

<div align = "center">
    <%= will_paginate @articles, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
</div>

app/views/users/new.html.erb
<h2 align = "center", class = "page-headers"> Hey there, let's get you signed up. </h2>\
<hr>


<%= render 'shared/errors', obj: @user %>

<div class = "row", id = "new-row">
    <div class = "col-xs-12">
        <%= form_for(@user, html: {class:'form-horizontal', role:'form'}) do |f| %>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :username %>
                </div> 
                <div class= "col-sm-8">
                    <%= f.text_field :username, class: "form-control" , placeholder: "Enter Username" %>
                </div>
            </div>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :email %> 
                </div>

                <div class= "col-sm-8">
                    <%= f.email_field :email, rows: 10, class: "form-control", placeholder: "Enter Email"%>
                </div>
            </div>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :password %>
                </div> 
                <div class= "col-sm-8">
                    <%= f.password_field :password, class: "form-control" , placeholder: "Enter Password" %>
                </div>
            </div>
            <div class = "form-group">
                <div class= "control-label col-sm-2">
                    <%= f.label :password_confirm %>
                </div> 
                <div class= "col-sm-8">
                    <%= f.password_field :password_confirm, class: "form-control" , placeholder: "Confirm Password" %>
                </div>
            </div>

                <div class = "form-group">
                    <div class = "col-sm-10 col-xs-offset-5">
                        <%= f.submit "Sign Up!", class: 'btn btn-primary btn-lg', id: 'create-btn'%>
                    </div>
                </div>
            </div>
        <% end %>

    <div class= "col-xs-4 col-xs-offset-5">
        <%= link_to "[Back to articles listing]", articles_path%>
    </div>
</div>

app/views/users/show.html.erb
<h2 align= "center", class= "page-headers"> Welcome to <%= @user.username %>'s post history</h2>
<hr>
<div class = "row">
    <div class= "col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user , size:150 %>
    </div>
</div>
<h4 align = "center", class = "page-headers"><%= @user.username%>'s articles </h4>

<%= render 'articles/article', obj: @user_articles %>
<div align = "center">
    <%= will_paginate @user_articles %>
</div>